# path to docker.exe and IP of docker host
$docker = "C:\Program Files\Docker\Docker\resources\bin\Docker.exe"
$dockerhost = "tcp://XX.XX.XX.XX:2375"

# path to certs generated by instructions on my blog 
# https://dbafromthecold.com/2017/02/22/remotely-administering-the-docker-engine-on-windows-server-2016/
# or via https://hub.docker.com/r/stefanscherer/dockertls-windows/
$certpath = ".........."

$tlscacert = "--tlscacert=$certpath\ca.pem"
$tlscert = "--tlscert=$certpath\server-cert.pem"
$tlskey = "--tlskey=$certpath\server-key.pem"

function Get-Containers {
    
   $fields = "ContainerId","Image","Command","Created","Status","Port","Name"
   
   . $docker --tlsverify $tlscacert $tlscert $tlskey -H $dockerhost ps -a |
       Select-Object -Skip 1 |
       ConvertFrom-String -Delimiter "[\s]{2,}" -PropertyNames $fields
}

function Get-Images {
   
   $fields = "Repository", "Tag", "ImageID", "Created", "VirtualSize"
   
   . $docker --tlsverify $tlscacert $tlscert $tlskey -H $dockerhost images |
      Select-Object -Skip 1 |
      ConvertFrom-String -Delimiter "[\s]{2,}" -PropertyNames $fields 
}

$containers = Get-Containers
$images = Get-Images 
